services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"  